### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'onClicked')

### ISSUE THREAD

**Issue by BurtHarris** [enisfr/orange-it-up-chrome-extension#1]
Hello.   Thanks for you article showing how to do extensions in typescript.  https://betterprogramming.pub/creating-chrome-extensions-with-typescript-914873467b65

When I attempt to use my extension, I'm getting an error when I install the extension, the msg reads: Uncaught TypeError: Cannot read properties of undefined (reading 'onClicked')

![Screenshot 2022-03-02 141545](https://user-images.githubusercontent.com/2715647/156459153-403745da-1f90-44a8-b133-285ab4b70da8.png)

**Comment by enisfr** [comment]
Hi. 
Thanks for the feedback.

_In order to use the chrome.action API, you need to specify a "manifest_version" of 3 or higher and include the action key in your [manifest file](https://developer.chrome.com/docs/extensions/mv3/manifest/)._ 

Please make sure that this is valid.
And also as far as I know `chrome.action.onClicked` event is available since **Chrome 88**.

If both of these are not working for you, I am afraid it will require a closer investigation.

You can also use `browser.browserAction.onClicked.addListener` instead of that.
